CalendarApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('events/', include('event_calendar.urls')),
]

event_calendar/urls.py
from django.urls import path
from . import views

app_name = 'event_calendar'

urlpatterns = [
    path('', views.event_list, name='event-list'),
    path('create/', views.event_create, name='event-create'),
    path('<int:id>/', views.event_detail, name='event-detail'),
    path('<int:id>/update/', views.event_update, name='event-update'),
    path('<int:id>/delete/', views.event_delete, name='event-delete'),
]

event_calendar/models.py
from django.db import models
from django.contrib.auth.models import User


class Event(models.Model):
    title = models.CharField(max_length=100)
    date = models.DateField()
    time = models.TimeField()
    description = models.TextField()
    participants = models.ManyToManyField(User)

    def __str__(self):
        return self.title

event_calendar/forms.py
from django import forms
from .models import Event


class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ('title', 'date', 'time', 'description')

event_calendar/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Event
from .forms import EventForm


def event_list(request):
    events = Event.objects.all()
    return render(request, 'event_calendar/event_list.html', {'events': events})


def event_detail(request, id):
    event = get_object_or_404(Event, id=id)
    return render(request, 'event_calendar/event_detail.html', {'event': event})


def event_create(request):
    if request.method == 'POST':
        form = EventForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('event_calendar:event-list')
    else:
        form = EventForm()
    return render(request, 'event_calendar/event_create.html', {'form': form})


def event_update(request, id):
    event = get_object_or_404(Event, id=id)
    if request.method == 'POST':
        form = EventForm(request.POST, instance=event)
        if form.is_valid():
            form.save()
            return redirect('event_calendar:event-detail', id=id)
    else:
        form = EventForm(instance=event)
    return render(request, 'event_calendar/event_update.html', {'form': form, 'event': event})


def event_delete(request, id):
    event = get_object_or_404(Event, id=id)
    if request.method == 'POST':
        event.delete()
        return redirect('event_calendar:event-list')
    return render(request, 'event_calendar/event_delete.html', {'event': event})

event_calendar/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <title>Event Calendar App</title>
</head>
<body>
  <nav>
    <a href="{% url 'event_calendar:event-list' %}">Event List</a>
  </nav>
  <hr>
  {% block content %}
  {% endblock %}
</body>
</html>

event_calendar/templates/event_calendar/event_create.html
{% extends 'base.html' %}

{% block content %}
  <h1>Create Event</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create</button>
        <a href="{% url 'event_calendar:event-list' %}">Back to Event List</a>
{% endblock %}

event_calendar/templates/event_calendar/event_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Event</h1>
  <p>Are you sure you want to delete the event "{{ event.title }}"?</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit">Delete</button>
  </form>
  <a href="{% url 'event_calendar:event-detail' event.id %}">Cancel</a>
{% endblock %}

event_calendar/templates/event_calendar/event_detail.html
{% extends 'base.html' %}

{% block content %}
  <h1>Event List</h1>
  <ul>
    {% for event in events %}
      <li><a href="{% url 'event_calendar:event-detail' event.id %}">{{ event.title }}</a></li>
    {% empty %}
      <li>No events available.</li>
    {% endfor %}
  </ul>
  <a href="{% url 'event_calendar:event-create' %}">Create New Event</a>
{% endblock %}

event_calendar/templates/event_calendar/event_list.html
{% extends 'base.html' %}

{% block content %}
  <h1>Event List</h1>
  <ul>
    {% for event in events %}
      <li><a href="{% url 'event_calendar:event-detail' event.id %}">{{ event.title }}</a></li>
    {% empty %}
      <li>No events available.</li>
    {% endfor %}
  </ul>
  <a href="{% url 'event_calendar:event-create' %}">Create New Event</a>
{% endblock %}

event_calendar/templates/event_calendar/event_update.html
{% extends 'base.html' %}

{% block content %}
  <h1>Edit Event</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Update</button>
  </form>
  <a href="{% url 'event_calendar:event-detail' event.id %}">Cancel</a>
{% endblock %}